twist_mux:
  ros__parameters:
    topics:
      keyboard:
        topic   : cmd_vel_keyboard
        timeout : 0.5
        priority: 100
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
